### ISSUE TITLE
vectorDrawables crash on older Android versions

### ISSUE THREAD

**Issue by joriswit** [starsep/Sokoban#2]
The line `vectorDrawables.useSupportLibrary = true` in `build.gradle` seems to cause a crash in older Android versions. For more information see this thread: https://stackoverflow.com/questions/36867298/using-android-vector-drawables-on-pre-lollipop-crash

Full error message:
```
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.starsep.sokoban.release/com.starsep.sokoban.release.activity.MainMenuActivity}: android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.Button
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2071)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
                      at android.app.ActivityThread.access$600(ActivityThread.java:138)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:213)
                      at android.app.ActivityThread.main(ActivityThread.java:4787)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.Button
                      at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:262)
                      at android.app.Activity.setContentView(Activity.java:1867)
                      at com.starsep.sokoban.release.activity.MainMenuActivity.setupUI(MainMenuActivity.kt:25)
                      at com.starsep.sokoban.release.activity.MainMenuActivity.onCreate(MainMenuActivity.kt:21)
                      at android.app.Activity.performCreate(Activity.java:5008)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2035)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:138) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:213) 
                      at android.app.ActivityThread.main(ActivityThread.java:4787) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:262) 
                      at android.app.Activity.setContentView(Activity.java:1867) 
                      at com.starsep.sokoban.release.activity.MainMenuActivity.setupUI(MainMenuActivity.kt:25) 
                      at com.starsep.sokoban.release.activity.MainMenuActivity.onCreate(MainMenuActivity.kt:21) 
                      at android.app.Activity.performCreate(Activity.java:5008) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2035) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:138) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:213) 
                      at android.app.ActivityThread.main(ActivityThread.java:4787) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/icon_continue.xml from drawable resource ID #0x7f070080
                      at android.content.res.Resources.loadDrawable(Resources.java:1923)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                      at android.widget.TextView.<init>(TextView.java:622)
                      at android.widget.Button.<init>(Button.java:107)
                      at android.widget.Button.<init>(Button.java:103)
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:262) 
                      at android.app.Activity.setContentView(Activity.java:1867) 
                      at com.starsep.sokoban.release.activity.MainMenuActivity.setupUI(MainMenuActivity.kt:25) 
                      at com.starsep.sokoban.release.activity.MainMenuActivity.onCreate(MainMenuActivity.kt:21) 
                      at android.app.Activity.performCreate(Activity.java:5008) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2035) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:138) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:213) 
                      at android.app.ActivityThread.main(ActivityThread.java:4787) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:886)
                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
                      at android.content.res.Resources.loadDrawable(Resources.java:1920)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:601) 
                      at android.widget.TextView.<init>(TextView.java:622) 
                      at android.widget.Button.<init>(Button.java:107) 
                      at android.widget.Button.<init>(Button.java:103) 
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                      at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:262) 
                      at android.app.Activity.setContentView(Activity.java:1867) 
                      at com.starsep.sokoban.release.activity.MainMenuActivity.setupUI(MainMenuActivity.kt:25) 
                      at com.starsep.sokoban.release.activity.MainMenuActivity.onCreate(MainMenuActivity.kt:21) 
                      at android.app.Activity.performCreate(Activity.java:5008) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2035) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:138) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:213) 
                      at android.app.ActivityThread.main(ActivityThread.java:4787) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                      at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by starsep** [comment]
Thanks for info, feel free to prepare pull request if you're willing - looks relatively trivial - needs some testing though.
Otherwise I'll fix that once I get some spare time.
